# Generated by Django 5.2.7 on 2025-11-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mockups", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mockup",
            name="font",
        ),
        migrations.RemoveField(
            model_name="mockup",
            name="text",
        ),
        migrations.RemoveField(
            model_name="mockup",
            name="text_color",
        ),
    ]
